# Generated by Django 5.2.10 on 2026-01-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0006_alter_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='units_collected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
