# Generated by Django 4.2.7 on 2026-01-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0007_blooddonate_units_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registerdb',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
